use_frameworks!

platform :ios, '8.0'

target 'WBExtension_Example' do
  pod 'WBExtension', :path => '../'

  target 'WBExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
